# Allo Movies project development docker-compose
version: "3"

services:
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  #                              N O D E   A P P                             #
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  app:
    build: ./app
    # env_file: ./cfg/.env
    image: app_node:lts-alpine
    container_name: app_ctn
    # restart: always
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    environment:
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=3001

  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  #                              N O D E   A P I                             #
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  api:
    build: ./api
    # env_file: ./cfg/.env
    image: api_node:latest
    container_name: api_ctn
    # restart: always
    depends_on:
      - db
    links:
      - db:db_host
    ports:
      - 3001:8080
    volumes:
      - ./api:/usr/src/app
    environment:
      - DB_HOST=db_host
      - DB_PORT=3306
      - DB_USER=acm
      - DB_PSWD=acm
      - DB_NAME=acm

  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  #                                 M Y S Q L                                #
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  db:
    # build: ./db_tmp
    # env_file: ./cfg/.env
    image: mysql:latest
    container_name: db_ctn
    # restart: always
    ports:
      - 3003:3306
    volumes:
      - ./db:/var/lib/mysql
    # - ./db_logs:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_USER=acm
      - MYSQL_PASSWORD=acm
      - MYSQL_DATABASE=acm

  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  #                            P H P M Y A D M I N                           #
  #--------------------------------------------------------------------------#
  #--------------------------------------------------------------------------#
  pma:
    # build: ./pma_tmp
    # env_file: ./cfg/.env
    image: phpmyadmin:latest
    container_name: pma_ctn
    # restart: always
    depends_on:
      - db
    links:
      - db:db_host
    ports:
      - 3002:80
    # volumes:
    # - ./pma:/sessions
    environment:
      - PMA_HOST=db_host
      - PMA_PORT=3306
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                            E N D  O F  F I L E                           #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
