# Allo Movies API development Dockerfile
FROM node:latest

# Change current working directory
WORKDIR /usr/src/app

# Install 'nodemon' command
RUN npm install -g nodemon

# Define exposed port
# EXPOSE 8080

# Run 'server.js' file with 'nodemon'
CMD [ "nodemon", "server.js" ]
